In [1]:
import numpy as np 
import pandas as pd 

In [2]:
df = pd.read_csv('../input/full-filled-brain-stroke-dataset/full_filled_stroke_data (1).csv', usecols=['age', 'avg_glucose_level', 'bmi', 'stroke'])

Using Age, Avg Glucose Level and BMI, I am predicting whether the Patient will undergo Brain Stroke or not.

In [3]:
df.sample(5)

age  avg_glucose_level        bmi  stroke
57   40.0              88.27  30.066805       0
108  19.0              72.39  26.284525       0
133  68.0             233.30  33.480734       0
173  75.0              83.88  28.402910       0
188  78.0             206.53  31.179276       0

In [4]:
from sklearn.model_selection import train_test_split

x_train,x_test, y_train, y_test = train_test_split(df.iloc[:, 0:3], df['stroke'], test_size=0.30, random_state=42)

In [5]:
x_train

age  avg_glucose_level        bmi
97   30.0              88.20  29.280322
31   78.0              60.67  27.086276
12   75.0             104.72  28.318273
35   79.0             114.77  27.243396
119  76.0              67.03  28.028716
..    ...                ...        ...
106  35.0              77.48  29.832593
14   51.0             165.31  30.491107
92   69.0             107.11  30.624832
179  17.0              92.97  26.527514
102  67.0              92.73  29.081489

[140 rows x 3 columns]

In [6]:
x_train.shape

(140, 3)

In [7]:
y_train

97     0
31     1
12     1
35     1
119    0
      ..
106    0
14     1
92     0
179    0
102    0
Name: stroke, Length: 140, dtype: int64

In [8]:
x_test.shape

(61, 3)

Applying Standardization on The 3 Numerical Columns:

In [9]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

x_train_transform = ss.fit_transform(x_train)
x_test_transform = ss.transform(x_test)

In [10]:
from sklearn.naive_bayes import BernoulliNB

bn = BernoulliNB()

bn.fit(x_train_transform, y_train)

BernoulliNB()

In [11]:
y_pred = bn.predict(x_test_transform)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
y_test.values

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion Matrix:')
print(cm)

Confusion Matrix:
[[51  0]
 [10  0]]


In [14]:
print('True Positive Values: {}'.format(cm[0][0]))
print('False Negative Values: {}'.format(cm[0][1]))
print('False Positives Values: {}'.format(cm[1][0]))
print('True Negative Values: {}'.format(cm[1][1]))

True Positive Values: 51
False Negative Values: 0
False Positives Values: 10
True Negative Values: 0


In [15]:
print('Actual Total Positives: {}'.format(cm[0][0] + cm[0][1]))
print('Actual Total Negatives: {}'.format(cm[1][0] + cm[1][1]))

Actual Total Positives: 51
Actual Total Negatives: 10


In [16]:
print('Predicted Total Positives: {}'.format(cm[0][0] + cm[1][0]))
print('Predicted Total Negatives: {}'.format(cm[0][1] + cm[1][1]))

Predicted Total Positives: 61
Predicted Total Negatives: 0


In [17]:
from sklearn.metrics import accuracy_score 
print ("Accuracy For Multivariate Bernoulli: ", accuracy_score(y_test, y_pred) * 100)

Accuracy For Multivariate Bernoulli:  83.60655737704919
